export const ReqApi = {
  Login: "/login",
  Register: "/register",
  LoginOut: "/loginout",
  LoginStatus: "/loginstatus",
  Update: "/update",
  Write: "/write",
  Article: "/article",
  Upload: "/upload",
  Articles: "/articles",
  Delete: "/delete",
  GetCategorys: "/projects-categorys",
  AddCategory: "/addProjectCategory",
  DeleteCategory: "/deleteCategory",
  UpdateCategory: "/updateCategory",
  AddProject: "/addProject",
  Projects: "/projects",
  DeleteProjects: "/delete-project",
};

